services:
  app:
    build: .
    container_name: react-app
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_database
      POSTGRES_PORT: 5432
    ports:
      - "5000:5000"
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: react-app-db
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
